### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [amznlabs/amazon-dsstne#12]
[Extra null pointer checks are not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") in [the function "NNLayer::Deallocate"](https://github.com/amznlabs/amazon-dsstne/blob/d59a973904d92a25304664616925cfc090b05a3e/src/amazon/dsstne/engine/NNLayer.cpp#L78 "Update candidate: NNLayer::Deallocate()").

**Comment by scottlegrand** [comment]
You are correct.  Old C habits die hard...

**Comment by tristanpenman** [comment]
Closing this issue since it has been resolved in source.
