### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [amznlabs/amazon-dsstne#13]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/amznlabs/amazon-dsstne/blob/d59a973904d92a25304664616925cfc090b05a3e/src/amazon/dsstne/utils/main.cpp#L29 "main() function")" does not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108 "Uncaught exceptions") like they are described by Danny Kalev?

**Comment by scottlegrand** [comment]
Overall, it's a conscious design decision to keep the error handling localized and readable (Yes I know Matthew Wilson does not agree with that) along with avoiding a lot of other fancier programming tricks unless absolutely needed in an age where C/C++ is no longer taught.  

His recommendations for a bulletproof main.cpp seem sensible though.  I'll be writing some more useful examples in the coming weeks that show how to make use of more of the existing features of the framework given most of the failure cases involve CUDA issues which can currently only be caught with if (error) like clauses (Check out cudaSafeCall in all the CUDA SDK examples to see what I mean).   I'd end up with an error check followed by manual exception throwing in this case.
