### ISSUE TITLE
ami-d6f2e6bc not found

### ISSUE THREAD

**Issue by llSourcell** [amznlabs/amazon-dsstne#18]
i couldn't find an instance on AWS called 'ami-d6f2e6bc' do you have a link to one?

**Comment by rgeorgej** [comment]
It is not an AWS Instance but AMI(Amazon Machine Image) you have to launch an instance with it

**Comment by llSourcell** [comment]
i couldnt find an AMI ID that matches ami-d6f2e6bc when i searched for public AMIs in my AWS console

**Comment by rgeorgej** [comment]
Which region  are you looking for? the AMI is currently available in us-east-1

**Comment by llSourcell** [comment]
ah ok I found it. But now when i try to launch a spot instance with that image i get an error. I'm launching it on a g2.2x large instance type

`The security group 'sg-f86ab683' does not exist in VPC 'vpc-f68b4691'
`

**Comment by llSourcell** [comment]
thanks that worked!

**Comment by rgeorgej** [comment]
Nice work with the tutorials that you have been making. I checked the free tier https://aws.amazon.com/free/  don't see any free tier for g2 Instances. I will take the feedback and let the respected people aware of it but I can't assure anything.

**Comment by llSourcell** [comment]
Cool, thanks!
