### ISSUE TITLE
'train' and 'predict' commands?

### ISSUE THREAD

**Issue by llSourcell** [amznlabs/amazon-dsstne#20]
I successfully spun up a GPU instance on EC2 using AMI you guys mentioned and uploaded this repo to it. I tried running the sample via run_movie_lens_sample.sh but it can't find the 'train' or 'predict' commands. How do i install these commands?

**Comment by rgeorgej** [comment]
https://github.com/amznlabs/amazon-dsstne/blob/master/docs/getting_started/setup.md

Please Update  the path 
#Add the mpiCC and nvcc compiler in the path
export PATH=/usr/local/openmpi/bin:/usr/local/cuda/bin:$PATH
make
export PATH=`pwd`/bin:$PATH

**Comment by llSourcell** [comment]
thanks!
