### ISSUE TITLE
Dataset Question

### ISSUE THREAD

**Issue by llSourcell** [amznlabs/amazon-dsstne#21]
Inside the ml20m-all file, it looks like this

2,1112486027:29,1112484676:32,1112484819:47,1112484727:50,1112484580:112,1094785740:151,1094785734:223,1112485573:253,1112484940:260,1112484826:293,1112484703:296,1112484767:318,1112484798:337,1094785709:367,1112485980:541,1112484603:589,1112485557:593,1112484661:653,1094785691:919,1094785621:924,

This looks like a listing of movies. Each movie has a list of features. But what are the features? This is only raw values, i'd like to know what these values mean. 

Also, is the example neural network doing collaborative filtering or content based filtering?

**Comment by rgeorgej** [comment]
Currently no movie  features are taken. Currently only 1/0 signals are supported from the wrapper script even though the Engine supports analog signals

This is collaborative filtering. Also you can see this as movie view based recommendation

**Comment by llSourcell** [comment]
@rgeorgej thanks so much for all the help, I really appreciate it. Check out the video I made using this library, I hope you like it! https://www.youtube.com/watch?v=eKmIVU8EUbw (a re-share by Amazon would be awesome if you found it interesting)

**Comment by rgeorgej** [comment]
Thanks for the video and it is really cool. People have already started sharing the videos
Nice work and much appreciated
