### ISSUE TITLE
NetCDF not working in AWS AMI

### ISSUE THREAD

**Issue by harik68** [amznlabs/amazon-dsstne#25]
Hi, I tried using DSSTNE by creating an instance with AMI Amazon DSSTNE (ami-d6f2e6bc). I am not able to run the command 'generateNetCDF -d gl_input -i ml20m-all -o gl_input.nc -f features_input -s samples_input -c' giving error 'generateNetCDF: command not found'. Do I need to install and configure NetCDF in the AMI before using it? 

Thanks
-Hari

**Comment by rgeorgej** [comment]
Did you try following the instruction at [Download and Build ](https://github.com/amznlabs/amazon-dsstne/blob/master/docs/getting_started/setup.md#download-the-code-and-build) .

The AMI is only  build with proper dependencies

**Comment by harik68** [comment]
Hi Rejith, I tried all the instructions in Download and Build and also tried instructions under Netcdf Setup. Still I am getting the same error 'generateNetCDF: command not found'. I am not finding any file with name 'generateNetCDF' to be included in the path. Not sure what the issue is.

-Hari

**Comment by rgeorgej** [comment]
Did you update the environment variable PATH variable mentioned at  [Download and Build ](https://github.com/amznlabs/amazon-dsstne/blob/master/docs/getting_started/setup.md#download-the-code-and-build) 
**export PATH=`pwd`/bin:$PATH**

**Comment by harik68** [comment]
Hi Renjith, it is working fine now. I think I didn't enter the make command last time. Thanks for your help.

**Comment by reachviji** [comment]
Hi Renjith, Even I am facing a similar issue. when I run the command 'generateNetCDF -d gl_input -i ml20m-all -o gl_input.nc -f features_input -s samples_input -c' giving error 'generateNetCDF: command not found'. 

Below are the steps followed:
1.  In the set up guide followed the option " Setup up on your own development machine" followed by "Download the code and build"
2. In the examples: executed the code: wget http://files.grouplens.org/datasets/movielens/ml-20m.zip and unzip -p ml-20m.zip ml-20m/ratings.csv > ml-20m_ratings.csv.
3. then changed the directory to samples/movielens and executed awk -f convert_ratings.awk ml-20m_ratings.csv > ml-20m_ratings. It gave an error as it was not able to recognise ml-20m_ratings. So re-executed step 2 in path samples/movielens and executed awk -f convert_ratings.awk ml-20m_ratings.csv > ml-20m_ratings
4. while executing generateNetCDF -d gl_input -i ml-20m_ratings -o gl_input.nc -f features_input -s samples_input -c, it ended up in an error generateNetCDF: command not found'. 

Can you please help me.

**Comment by spacelover1** [comment]
So the engine has built successfully on container, but after running this line in the example document `generateNetCDF -d gl_input -i ml-20m_ratings -o gl_input.nc -f features_input -s samples_input -c`, the similar error comes up `generateNetCDF: command not found`.

I got some errors for `netcdf` using this Dockerfile so I added these lines for installing it:
```
RUN wget http://archive.ubuntu.com/ubuntu/pool/universe/n/netcdf-cxx/netcdf-cxx_4.3.0+ds.orig.tar.gz && \
	tar xzf netcdf-cxx_4.3.0+ds.orig.tar.gz && \
	cd netcdf-cxx4-4.3.0 && \
	./configure --disable-filter-testing && \
	make && \
	make install
```
Any suggestions to solve this?
Regards,
