### ISSUE TITLE
Train problem in AWS AMI

### ISSUE THREAD

**Issue by parvanesh** [amznlabs/amazon-dsstne#26]
Hello all,
I am using the AWS instance for the setup, i have a problem when running the training part:

>  train -c config.json -i gl_input.nc -o gl_output.nc -n gl.nc -b 256 -e 10
> Train will use configuration file: config.json
> Train will use input data file: gl_input.nc
> Train will use output data file: gl_output.nc
> Train will produce networkFileName: gl.nc
> Train will use batchSize: 256
> Train will use number of epochs: 10
> Train alpha 0.025, lambda 0.0001, mu 0.5.Please check CDL.txt for meanings
> GpuContext::Startup: Process 0 out of 1 initialized.
> modprobe: ERROR: could not insert 'nvidia': No such device
> cudaGetDeviceCount failed no CUDA-capable device is detected

However, there are several versions of nvidia ...what can be the issue?
Thanks in advance!

**Comment by parvanesh** [comment]
Ah!,  it was a mistake in the choosing the right sintance which is supporting GPU!

**Comment by rgeorgej** [comment]
@parvanesh we missed out in the documentation that this package is only supported on GPU based (g2.2xlarge,g2.8xlarge) AWS instances.I have updated the documentation at https://github.com/amznlabs/amazon-dsstne/blob/master/docs/getting_started/setup.md#setup-on-aws .

Please launch a GPU based instance and let us know if  you still face this issue

**Comment by parvanesh** [comment]
Thanks! exactly few seconds ago i've posted the same. Yes, launching a GPU based instance solved the issue
