### ISSUE TITLE
Fix data split for multi-gpu

### ISSUE THREAD

**Issue by rybakov** [amznlabs/amazon-dsstne#29]
Sparse indexes of data are splitted correctly between gpus, but data are copied as if it was a single gpu. It is a bug.

**Comment by scottlegrand** [comment]
I don't actually think that's a bug.

You're right that process 0 maintains a full copy of the sharded data.

But that's not true of the other processes.  Am I missing something?

**Comment by scottlegrand** [comment]
In fact at the end, process 0 cleans itself up:

// Finally derive local shard
                vector<uint64_t> vTempSparseStart    = _vSparseStart;
                vector<uint64_t> vTempSparseEnd     = _vSparseEnd;
                vector<uint32_t> vTempSparseIndex   = _vSparseIndex;
                vector<T> vTempSparseData           = _vSparseData;
                _vSparseIndex.resize(0);
                _vSparseData.resize(0);
                _vSparseStart.resize(_examples);
                _vSparseEnd.resize(_examples);
                for (uint32_t j = 0; j < _examples; j++)
                {
                    _vSparseStart[j]                = _vSparseIndex.size();
                    for (uint64_t k = vTempSparseStart[j]; k <
vTempSparseEnd[j]; k++)
                    {
                        if ((vTempSparseIndex[k] >= _minX) &&
(vTempSparseIndex[k] < _maxX))
                            _vSparseIndex.push_back(vTempSparseIndex[k]);
                        if (!(_attributes & Boolean))
                            _vSparseData.push_back(vTempSparseData[k]);
                    }
                    _vSparseEnd[j]                  = _vSparseIndex.size();
                }

No?

**Comment by rybakov** [comment]
Yes process 0 keeps all data set. It also does the split of the data between different processes.

Below we split the indexes between different processes (and it is correct)
if ((_vSparseIndex[k] >= xmin) && (_vSparseIndex[k] < xmax))
    vLocalSparseIndex.push_back(_vSparseIndex[k] - xmin);

But belowpart of code is not under condition "(_vSparseIndex[k] >= xmin &&_vSparseIndex[k] < xmax)" and it looks like a bug.
if (!(_attributes & Boolean))
    vLocalSparseData.push_back(_vSparseData[k]);

For example if we have data:
_vSparseIndex 0 1 2 3 4 5 6 7
_vSparseData  0 1 2 3 4 5 6 7

And we split it among two process, 
so that xmin = 0 xmax = 4 for process 0 and
xmin = 4 xmax = 8 for process 1 than indexes and data will be splitted like this:
for process 0 (xmin = 0 xmax = 4):
vLocalSparseIndex = 0 1 2 3
vLocalSparseData = 0 1 2 3 4 5 6 7

for process 1 (xmin = 4 xmax = 8):
vLocalSparseIndex = (4-xmin,  5-xmin,  6-xmin,  7-xmin ) = 0 1 2 3
vLocalSparseData = 0 1 2 3 4 5 6 7

Above Indexes are splitted correctly, but not the data, because they are not splitted but just copied to all process. It should be like this:
for process 0
vLocalSparseIndex = 0 1 2 3
vLocalSparseData = 0 1 2 3

for process 1
vLocalSparseIndex = 0 1 2 3
vLocalSparseData =  4 5 6 7

So the fix is: put data split under condition (_vSparseIndex[k] >= xmin &&_vSparseIndex[k] < xmax)
Did I get it wrong?

**Comment by scottlegrand** [comment]
Yes, you got it right.  The diff viewer was in unified mode making this
look really confusing.  Nice catch!

**Comment by rgeorgej** [comment]
I merged the request
