### ISSUE TITLE
Issue when follow the example

### ISSUE THREAD

**Issue by vinhqdang** [amznlabs/amazon-dsstne#34]
Hello all,

I am following the example with movielens and got the error

```
generateNetCDF -d gl_input -i ml20m-all -o gl_input.nc -f features_input -s samples_input -c
generateNetCDF: error while loading shared libraries: libnetcdf_c++4.so.1: cannot open shared object file: No such file or directory
```

I installed all the libraries required in the homepage (I am running Ubuntu 14.04 with GPU CUDA). Could you suggest some hints to figure out what did I do wrong?

Thanks a lot,

**Comment by rgeorgej** [comment]
Can you search for the existence of libnetcdf_c++4.so.1 in your machine
```bash
sudo find / -name libnetcdf_c++4.so.1
```
and the directory to LD_LIBRARY_PATH environment variable

**Comment by vinhqdang** [comment]
Here is the result

```
/home/ubuntu/netcdf-cxx4-4.2/cxx4/.libs/libnetcdf_c++4.so.1
/usr/local/lib/libnetcdf_c++4.so.1
```

**Comment by rgeorgej** [comment]
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/

**Comment by benitezmatias** [comment]
@vinhqdang, please let us know if your issue is solved. Otherwise this issue will be closed in the next 48 hrs.

**Comment by vinhqdang** [comment]
oops, I forgot, I will come back soon on this

**Comment by tristanpenman** [comment]
Closing this issue for now since it has been over a month since the last update.

**Comment by jxlijunhao** [comment]
以在 ~/.bashrc 或者 ~/.bash_profile 中加入 export 语句，前者在每次登陆和每次打开 shell 都读取一次，后者只在登陆时读取一次。我的习惯是加到 ~/.bashrc 中，在该文件的未尾，可采用如下语句来使设置生效：

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
