### ISSUE TITLE
What does the denoising parameter do?

### ISSUE THREAD

**Issue by jarfa** [amznlabs/amazon-dsstne#35]
To the extent that documentation covers it (https://github.com/amznlabs/amazon-dsstne/blob/master/docs/getting_started/LDL.txt#L23) it's far from clear. Some operation is performed on input events with some probability p?

**Comment by scottlegrand** [comment]
Google denoising auto encoder

TLDR: lips 1 inputs to 0 with probability p

**Comment by jarfa** [comment]
You meant "flips". And thanks, it's doesn't appear very complicated.

**Comment by scottlegrand** [comment]
Yes, but Google autocorrect disagreed with me :-).
