### ISSUE TITLE
Trouble with AWS GPU instance and Docker

### ISSUE THREAD

**Issue by hamukazu** [amznlabs/amazon-dsstne#36]
Hello,

I made an AWS GPU instance from the ami called "amazon-dsstne" (ami-7a0df81a) and made docker image of dsstne there. I followed the example in the document. Then when running "train", it fails with the following error message:

modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/3.13.0-83-generic/modules.dep.bin'
cudaGetDeviceCount failed unknown error

Thanks.

**Comment by rgeorgej** [comment]
When running inside the Docker you need to ensure that nvidia driver module is loaded in the host. We normally run deviceQuery to load the nVidia Kernel

1. Launched the instance with AMI ami-d6f2e6bc
2. Build DeviceQuery and run it with the following instructions in the AMI
```bash
cd NVIDIA_CUDA-7.0_Samples/1_Utilities/deviceQuery
make
./deviceQuery
```
3 .  sudo docker run -it --privileged amazon/dsstne /bin/bash

**Comment by rgeorgej** [comment]
Because of the confusion I have also updated the setup documentation for further referrence. 

Please do let us know if you are still blocker

**Comment by hamukazu** [comment]
Thank you for a very quick reply.

> 3 . sudo docker run -it --privileged amazon/dsstne /bin/bash

I found the reason. It was because I didn't say "sudo" before the "docker".

Now everything is working.

I think it should be explained in the setup document. It is not clear for people who are not familiar with docker or cuda.

**Comment by Claire-Kelley** [comment]
I am having a similar problem (and hamukazu's solution doesnt work for me) 

I am following the instructions in the setup file for running dsstne through docker. 

In my aws ami ./deviceQuery works (it returns Detected 4 CUDA Capable device(s) and then lists them and finally says that it passed)  
i can look at my device and driver with the command nvidia-smi and everything appears to be correct. 

I then build the docker image and start it using: 

sudo docker run -it --privileged amazon/dsstne /bin/bash

however when I try to run the sample code in the docker container all lines run up until the train step which returns the error: 
GpuContext::Startup: Process 0 out of 1 initialized.
cudaGetDeviceCount failed no CUDA-capable device is detected

If I try to list nvidia devices using the command nvidia-smi  it returns the errors: 
Failed to initialize NVML: GPU access blocked by the operating system

Do you have any advice about how I might fix this?

**Comment by rgeorgej** [comment]
Did you install the same driver version as it is inside the docker?

**Comment by rgeorgej** [comment]
@Claire-Kelley Are you still Blocked with this

**Comment by Claire-Kelley** [comment]
Sorry to respond slowly! Yes I had installed the same driver version as in the docker. 

I never did figure out what was causing my particular issue- I think I must have installed something improperly and not been able to uninstall it. I ended up wiping the instance and starting again with a new one (which worked as expected). Thanks for your help!
