### ISSUE TITLE
The code promises to use SGD as the default training mode, but then doesn't.

### ISSUE THREAD

**Issue by jarfa** [amznlabs/amazon-dsstne#40]
To quote lines [138-140 in Train.cpp](https://github.com/amznlabs/amazon-dsstne/blob/master/src/amazon/dsstne/utils/Train.cpp#L138-L140)
```
// Set to default training mode SGD.
TrainingMode mode=Nesterov;
pNetwork->SetTrainingMode(mode);
```

Elsewhere in the help files it also says that the default is SGD. And after looking through the code, I can't figure out how the user can actually set the optimization mode. Before you reply "just put it in the .config file", that doesn't work - see https://github.com/amznlabs/amazon-dsstne/issues/39

The default should either be changed to SGD, or the documentation should change. And it should be clearer how a user can specify the training optimization mode.

**Comment by rgeorgej** [comment]
Sorry about that and i have updated the code for that. Training parameters configured through CDL is not supported yet but only through code
https://github.com/amznlabs/amazon-dsstne/blob/master/docs/getting_started/userguide.md#optimization
