### ISSUE TITLE
Error: invalid device function launching kernel kScaleAndBias_kernel

### ISSUE THREAD

**Issue by oyotong** [amznlabs/amazon-dsstne#41]
Hi All,

I am following the example with movielens and got the error as below:

`train -c config.json -i gl_input.nc -o gl_output.nc -n gl.nc -b 256 -e 10`

NNNetwork::NNNetwork: 1 input layer
NNNetwork::NNNetwork: 1 output layer
NNWeight::NNWeight: Allocating 13697024 bytes (128, 26752) for weights between Input and Hidden
**Error: invalid device function launching kernel kScaleAndBias_kernel**
GpuContext::Shutdown: Shutting down cuBLAS on GPU for process 0
GpuContext::Shutdown: CuBLAS shut down on GPU for process 0
GpuContext::Shutdown: Shutting down cuRand on GPU for process 0
GpuContext::Shutdown: CuRand shut down on GPU for process 0
GpuContext::Shutdown: Process 0 out of 1 finalized.

![image](https://cloud.githubusercontent.com/assets/9816096/16113007/a22f7fd8-33ec-11e6-9879-0bcba151ce73.png)

Could you suggest some hints to figure out what did I do wrong?

Thanks a lot.

**Comment by scottlegrand** [comment]
I believe that's a Fermi class GPU (GF119 according to the link below).
DSSTNE requires Kepler (2012) or later GPUs due to the use of the __shfl
instruction in its CUDA kernels which was introduced with GK104.

https://www.techpowerup.com/gpudb/821/geforce-gt-610

**Comment by scottlegrand** [comment]
Interestingly, DSSTNE should have kvetched about this during GPU
initialization.  I'll figure out why it didn't.

**Comment by oyotong** [comment]
Got it, thank you!

Oh, I need to upgrade the card.
How about 'GeForce GTX 760M'? Could you suggest some card?
Only for study DSSTNE.

Thanks again!

**Comment by headhunters27** [comment]
I

**Comment by scottlegrand** [comment]
Gtx 760 ought to do.

**Comment by oyotong** [comment]
Got it, thanks a lot!

**Comment by rajserc** [comment]
Getting similar error on volta, any idea on how to workaround this ?
`
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.81                 Driver Version: 384.81                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:07:00.0 Off |                    0 |
| N/A   36C    P0    43W / 300W |     10MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

`
