### ISSUE TITLE
How to improve the ranking rate?

### ISSUE THREAD

**Issue by oyotong** [amznlabs/amazon-dsstne#42]
Hi All,

I trained the network using blow data,

11032	4153892,65002142:3462821,63988456:2213877,64982398:2213877,65009021:2213877,65272075:4040029,65002223:...
Note: 11032 is user_id, 4153892 is sku_no, 65002142 is order_no

but got very low ranking rate, could you have any suggestions?

11032	4431085,**0.014**:3970704,**0.014**:4231712,0.013:3941914,0.013:4093510,0.012:4074152,0.012:4431424,0.012:4258254,0.012:3968476,0.011:3968475,0.011:

Thanks

**Comment by scottlegrand** [comment]
More details?

**Comment by oyotong** [comment]
About the Layer:
`"Layers" : [
        { "Name" : "Input", "Kind" : "Input", "N" : "auto", "DataSet" : "gl_input", "Sparse" : true }, 
        { "Name" : "Hidden", "Kind" : "Hidden", "Type" : "FullyConnected", "N" : 128, "Activation" : "Sigmoid", "Sparse" : true },
        { "Name" : "Output", "Kind" : "Output", "Type" : "FullyConnected", "DataSet" : "gl_output", "N" : "auto", "Activation" : "Sigmoid", "Sparse" : true }
    ],`

Abount commands:
`generateNetCDF -d gl_input -i dss_cpo_sku -o gl_input.nc -f features_input -s samples_input -c
generateNetCDF -d gl_output -i dss_cpo_sku -o gl_output.nc -f features_output -s samples_input -c
train -c config.json -i gl_input.nc -o gl_output.nc -n gl.nc -b 128 -e 10
predict -b 128 -d gl -i features_input -o features_output -k 10 -n gl.nc -f dss_cpo_sku -s recs -r dss_cpo_sku`

About data: Number of samples is more than 16000.

**Comment by scottlegrand** [comment]
Have you tried any other sorts of classifiers with it?  What's the # of classes?  And what's the average # of data points per sample?

**Comment by scottlegrand** [comment]
Also take a look at the two networks I posted to issue 24.  They both seem to get better than state of the art perf on MovieLens 20M.

**Comment by oyotong** [comment]
Thanks for your suggestions!
Use the below configuration works fine.

`"Denoising" : {
		"p" : 0.4
	},

	"ScaledMarginalCrossEntropy" : {
		"oneTarget" : 1.0,
		"zeroTarget" : 0.0,
		"oneScale" : 30.0,
		"zeroScale" : 1.0
	},
	"Layers" : [
		{ "Name" : "Input0", "Kind" : "Input", "N" : "auto", "DataSet" : "gl_input", "Sparse" : true }, 
		{ "Name" : "Hidden", "Kind" : "Hidden", "Type" : "FullyConnected", "Source" : [ "Input0" ], "N" : 256, "Activation" : "Sigmoid", "Sparse" : true },      
		{ "Name" : "Output", "Kind" : "Output", "Type" : "FullyConnected", "Source" : [ "Hidden" ], "DataSet" : "gl_output", "N" : "auto", "Activation" : "Sigmoid", "Sparse" : true }
	],

	"ErrorFunction" : "ScaledMarginalCrossEntropy"`
