### ISSUE TITLE
How to continue learning?

### ISSUE THREAD

**Issue by oyotong** [amznlabs/amazon-dsstne#43]
Hi,

I have used the 'train -n gl.nc ...' to get a network file. In the future, if I have more new sample data can be used to training. How to continue training? I used the command 'train -n gl.cn ..' again, but got below error:

Error: Network file already exists: gl.nc

Thanks.

**Comment by rgeorgej** [comment]
You have to delete the gl,nc before retraining  if you are using the same file for checkpointing your network

**Comment by oyotong** [comment]
Thanks for your response!

If I just need add some new samples for training, I think that need not to train the old samples again.

Thanks.

**Comment by rgeorgej** [comment]
Yes you are correct

**Comment by oyotong** [comment]
But how can do?

Thanks.

**Comment by rgeorgej** [comment]
```bash
rm  gl..nc
```
before you train a different model

**Comment by oyotong** [comment]
can I use new samples data to train the old network?

**Comment by rgeorgej** [comment]
I think i understand your question more now . I  see that  you want to restarted training from an already trained model.

Its not supported in the utilities we have provided  now.

But you should take a look at https://github.com/amznlabs/amazon-dsstne/blob/master/src/amazon/dsstne/utils/Predict.cpp#L214 on how to load an existing Network 

and replace it at https://github.com/amznlabs/amazon-dsstne/blob/master/src/amazon/dsstne/utils/Train.cpp#L126 

Is this what you wanted ?

**Comment by oyotong** [comment]
Yes, that is my wanted. Thank you!
