### ISSUE TITLE
AWS Machine Learning and DSSTNE

### ISSUE THREAD

**Issue by katp4** [amznlabs/amazon-dsstne#46]
First of all, apologies if this is the wrong place to post this question. I would appreciate it if you could point me to the correct forum.

I am new to ML and NNs and i'm currently researching what's available out there so please excuse my ignorance. I got a couple of questions that i would like to ask the community.

I was wondering what the difference is between AWS Machine Learning (https://aws.amazon.com/machine-learning/) and DSSTNE. Does AWS ML use DSSTNE in the background? Are they completely different technologies?

Google's Parsey McParseface uses Tensorflow behind the scenes. Is DSSTNE what Amazon's Alexa uses?

Theoretically, can i integrate  ParseyMcParseface/Alexa(AVS) with DSSTNE?

Thank you very much

**Comment by scottlegrand** [comment]
1. This is not Amazon Machine Learning.  This is the framework we developed at Amazon for generating product recommendations.  As the lead developer of DSSTNE (and no longer at Amazon), I can assert nothing has been left out of it.  The only things we haven't provided are the actual networks in use and the data sets to which they are applied.

2. Porting any TensorFlow network to DSSTNE would make an interesting project.  We currently lack CNN and LSTM/GRU support, but recent releases like the "Wide and Deep" network would port directly just by changing a line or two of the right JSON network config file.  It would also likely run 3-30x faster in DSSTNE as well as make much more efficient use of memory.

3. I cannot comment about Alexa other than to say I think it's awesome.

4.  CNN and LSTM/GRU support are coming soon.

**Comment by katp4** [comment]
Hey Scott,

Thanks for pointing me in the right direction and helping me understand! If you are new to this you can easily get lost in the plethora of information. 

Just wanted to say you've all done an amazing job on this and I'm looking forward to understanding it better and using it in my own application.

And i agree... Alexa is awesome :)
