### ISSUE TITLE
any "convolutional" support yet?

### ISSUE THREAD

**Issue by ameenetemady** [amznlabs/amazon-dsstne#48]
Hi, 
I have a network with sparse 1d input vectors and want first layer to be convolutional. Can I do that with dsstne?
The api does mention "Convolutional" but the documentation mentions it's not supported for "image", while my input is not image.

Would you please clarify?
Thank you.
Ameen.

**Comment by rgeorgej** [comment]
Covolutional Layer is not supported but the time line for this is within a month,

**Comment by ameenetemady** [comment]
great, thanks for your quick response.
