### ISSUE TITLE
Machine Learning

### ISSUE THREAD

**Issue by vinunoby** [amznlabs/amazon-dsstne#49]
Currently we are looking for Recommendation Engine suitable for online marketing .We came across AWS Machine Learning where we have to submit our input file containing user item relation along with its targeted to generate a model .Mortar Recommendation Engine which is not currently available interacts with AWS and generate target value which can be passed to the Machine Learning Process and Prediction will be available ...In DSSTNE how is it working ..Im totally confused.

**Comment by scottlegrand** [comment]
Could you clarify the question?  The ancillary code provided shows how to input user data for both input and output.  It's up to you take it further.  I'm happy to help, but I need more specific information than this.

**Comment by romerocesar** [comment]
@vinunoby The Amazon Machine Learning service on AWS does not support recommendations at the moment. DSSTNE is an excellent engine for recommendations, and this repo includes instructions on how to set up a GPU host on AWS to run it. Have you gone through the initial setup?

**Comment by tristanpenman** [comment]
Closing this issue for now since it has been over a month since the last update.
