### ISSUE TITLE
GPU memory consumption for large example sets

### ISSUE THREAD

**Issue by Borisvl** [amznlabs/amazon-dsstne#52]
I have tried to train an autoencoder similar to the movielens example with a couple of million sparse training examples and ran into GPU memory allocation errors. After reducing the number of examples the network could be trained just fine. After taking a look at the code, it seems that the whole training data is saved on the GPU for the input and output layers (this seems to happen in the NNDataSet::Shard function). 
Is there any way to get around this limitation? In theory, shouldn't it be enough to upload only the data for the current mini-batch?

**Comment by scottlegrand** [comment]
Add a second GPU.

Or shortly by a pascal GPU and turn on streaming data.

What kind of GPU are you currently using and how big is the dataset?

**Comment by rgeorgej** [comment]
DSSTNE do load the entire data to the memory to speed up.
What is the batch size you are using ??
Is it possible to reduce the batch size and still put all the examples you want ?
What kind of GPU do you use ?

**Comment by Borisvl** [comment]
I ran the example on a AWS g2.2xlarge instance. The batch size is 256, it works if I reduce it to 64 but then runtime is much longer. 

I understand that I can distribute the computation to more GPUs, but is there any (planned?) support for streaming the examples in batches to the GPU (without Pascal architecture) like other frameworks support? Since uploading millions of examples to the GPU takes only a few seconds, compared to the learning which takes hours, I guess the overhead is almost negligible.

**Comment by scottlegrand** [comment]
Run on 4 GPUS using g2.8xlarge...

Or buy a Pascal GPU.  When GTX 1080s are $600, it's hard to justify the
100% free OSS engineering to make streaming work on their predecessors.

I receive no funding from Amazon or any other agency.  I promise to provide
streaming from Pascal GPUs and up, but in return, you have to put some skin
in the game, OK?  Or run on g2.8lxarge of course right now...

**Comment by tristanpenman** [comment]
Closing this issue, as it has been several months since the last comment and this is basically a GPU architecture limitation that is fixed by throwing more GPUs (or more recent GPUs) at the problem.
