### ISSUE TITLE
Improved isolation of GPU and non-GPU functionality in utils and headers

### ISSUE THREAD

**Issue by tristanpenman** [amznlabs/amazon-dsstne#54]
I have been working on some more unit tests for DSSTNE. One of the issues that I have run into is how to structure the test suite so that parts of the code that do not depend on CUDA could be executed in a CI environment such as Travis CI.

The approach I'm exploring at the moment is to make more aggressive use of forward declarations in the header files, such that the test suite could be built without a full CUDA installation. I wanted to raise an issue to get the DSSTNE team's thoughts before diving too deep, or submitting a PR.

I've also noticed a few other things that could be improved, such as moving 'using namespace x' declarations from header files to source files. These are all minor changes, but will help with isolation between 'utils' and 'engine'.

**Comment by tristanpenman** [comment]
For what it's worth, I have successfully built and run the current 'unittest' test suite on Travis CI. So that could definitely provide a good foundation for expanding the unit tests to cover a larger portion of DSSTNE's non-GPU functionality.

**Comment by scottlegrand** [comment]
Keeping the build of DSSTNE simple is a key goal.  I'd need more detail
describing the changes you propose before deciding on it.  If it's
non-invasive to building DSSTNE for training/inference, I'm probably all
for it.

**Comment by tristanpenman** [comment]
The changes to support Travis CI are pretty non-invasive. I haven't opened a PR for that yet, but you can see the progress here:
https://github.com/amznlabs/amazon-dsstne/compare/master...tristanpenman:travis-ci

This branch adds a .travis.yml file for Travis CI, and includes the changes necessary to build the unit tests using CMake.

The CMakeLists file currently lives in the tst/unittests directory, since that is the only place where it currently provides value. And given that CMake builds can be hierarchical, it will be relatively easy to work back towards the root as the build is more complete.

**Comment by tristanpenman** [comment]
As for the header files, I'm still experimenting with some different approaches on a local branch, but two initial changes that seem appropriate to me are:
 - in any headers that are shared between builds/binaries, use the `std::` prefix instead of `using namespace std`
 - and add `using namespace std` to source files, where necessary

Then it would be a matter of identifying any classes/typedefs that need to be shared between tests and engine code and deciding how to split those up while keeping everything nice and lean.

**Comment by tristanpenman** [comment]
Closing this issue for now as the initial Travis CI changes have been merged as part of PR https://github.com/amznlabs/amazon-dsstne/pull/57 with additional changes in later PRs.

As for refactoring header files, this was discussed offline and it is clear that this can be tackled as a continuous improvement effort. The changes made as part of PR https://github.com/amznlabs/amazon-dsstne/pull/60 serve as a good example for how we can approach these improvements going forward.
