### ISSUE TITLE
documentation clarification

### ISSUE THREAD

**Issue by grantbabb** [amznlabs/amazon-dsstne#56]
Your docs say
Hidden Hidden Layers are Layers which connect between layers. It Does require a DataSet but rather a Source. If Source is not mentioned then the previous Layer is taken as Source

I think it might be changed to
Hidden Hidden Layers are Layers which connect between layers. It does not require a DataSet but rather a Source. If Source is not mentioned then the previous Layer is taken as Source

**Comment by romerocesar** [comment]
Feel free to send a pull request with any improvements.
