### ISSUE TITLE
Fail to build on the AMI.

### ISSUE THREAD

**Issue by Keisuke69** [amznlabs/amazon-dsstne#58]
After[ this commit](https://github.com/amznlabs/amazon-dsstne/commit/e3b2bd7238da1863df2c33eb864d8ee2d7d588f0), I can't build DSSTNE on the AMI. Or setup instruction doesn't work well.

The following is the error message.
'GpuTypes.h:23:19: fatal error: cudnn.h: No such file or directory'

**Comment by scottlegrand** [comment]
cuDNN needs to be added to the AMI, cuDNN can be obtained here...

https://developer.nvidia.com/cudnn

I *think* you need to do this yourself due to the terms for acquiring
cuDNN.  For now, you can comment out all terms invoking cudnn, but the next
major check-in enabling convolutional networks will make use of it.

Scott

**Comment by juliensimon** [comment]
Hi,

I'm using the AMI as well (ami-d6f2e6bc). I downloaded and installed cuDNN v4 (Feb 10, 2016 for CUDA 7.0 and later).

Build fails with : 

ubuntu@ip-172-31-51-22:~/amazon-dsstne/src/amazon/dsstne$ make
cd engine && make
************  RELEASE mode ************
make[1]: Entering directory `/home/ubuntu/amazon-dsstne/src/amazon/dsstne/engine'
nvcc -use_fast_math --ptxas-options="-v" -gencode arch=compute_50,code=sm_50 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_60,code=sm_60 -DOMPI_SKIP_MPICXX -std=c++11 -I/usr/local/cuda/include -IB40C -IB40C/KernelCommon -I/usr/local/include -I/usr/local/openmpi/include -I/usr/include/jsoncpp -I../utils -I../engine  -c kernels.cu
nvcc fatal   : Unsupported gpu architecture 'compute_60'
make[1]: *** [kernels.o] Error 1
make[1]: Leaving directory `/home/ubuntu/amazon-dsstne/src/amazon/dsstne/engine'

ubuntu@ip-172-31-51-22:~/amazon-dsstne/src/amazon/dsstne$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Mon_Feb_16_22:59:02_CST_2015
Cuda compilation tools, release 7.0, V7.0.27

**Comment by juliensimon** [comment]
Quick fix: branch at the parent commit (as pointed out by @Keisuke69)

git branch stable 95ffe304312269087a39dcd787850285ca3be82a
git checkout stable
make

You might want to update the documentation, if you have the time ;) 

Looking forward to the next releases!

**Comment by juliensimon** [comment]
Quick fix (?) : branch at 9f08739b62b3d3f7c742e30f83c55b65aaf7920b. The next commit introduces architecture "compute_60" which is unsupported by the bundled 'nvcc' :-/

Revised build instructions:
git clone https://github.com/amznlabs/amazon-dsstne.git
git branch stable 9f08739b62b3d3f7c742e30f83c55b65aaf7920b
git checkout stable
cd amazon-dsstne/src/amazon/dsstne
#Add the mpiCC and nvcc compiler in the path
export PATH=/usr/local/openmpi/bin:/usr/local/cuda/bin:$PATH
make
export PATH=`pwd`/bin:$PATH

Tested with the 'movies' example. Works fine 👍

**Comment by brunosez** [comment]
Thanks Julien ! 
works fine on movies, also relatively quick.
may be it may exists a table summarizing all good combination of cuda, cudnn, driver as for example the docker version is stucked to a nvidia driver version.
Regards
Bruno

**Comment by danilop** [comment]
Minor fix: You need to branch/checkout after you changed directory, to be in a git repository.

Revised build instructions:
git clone https://github.com/amznlabs/amazon-dsstne.git
cd amazon-dsstne/src/amazon/dsstne
git branch stable 9f08739
git checkout stable
#Add the mpiCC and nvcc compiler in the path
export PATH=/usr/local/openmpi/bin:/usr/local/cuda/bin:$PATH
make
export PATH=pwd/bin:$PATH

**Comment by tristanpenman** [comment]
As mentioned in issue https://github.com/amznlabs/amazon-dsstne/issues/96...

> My recent changes to the Dockerfile included in this repo should address the cuDNN-related compiler errors. The new Dockerfile inherits from one of NVIDIA's public Docker images, which has CUDA 7.5 + cuDNN 5.1 installed. Note that you'll have to build the Docker image yourself, as it the end user's responsibility to accept the NVIDIA's EULA.
> 
> The updated Docker image is intended to be used via nvidia-docker. If you're using AWS, you can create an EC2 instance from our latest AMI (ami-25c0eb32), which has nvidia-docker pre-installed. Details can be found in the [Setup Guide](https://github.com/amznlabs/amazon-dsstne/blob/master/docs/getting_started/setup.md).
> 
> The Makefile has also been updated to remove some compiler flags that assumed CUDA 8 would be available.
