### ISSUE TITLE
Can we use dsstne(or similar functions) in the AWS Machine Learning

### ISSUE THREAD

**Issue by oyotong** [amznlabs/amazon-dsstne#63]
Hi,

As it said in title, we hope using the AWS Machine Learning to do product recommendations(top-N, and base on deep learning). But we found the ML just be used to predict whether a customer will buy a product.

Thanks,
Andy.

**Comment by romerocesar** [comment]
DSSTNE is unrelated to the AWS Amazon Machine Learning service today, and we cannot comment on the roadmap of the service here.

You can certainly deploy DSSTNE on EC2 instances and use it to generate recommendations by using either the AMI or Docker image following the [setup instructions](https://github.com/amznlabs/amazon-dsstne/blob/master/docs/getting_started/setup.md)

**Comment by oyotong** [comment]
Got it, thanks for your suggestions!
