### ISSUE TITLE
Non-empty .bash_history present on AMI

### ISSUE THREAD

**Issue by juliensimon** [amznlabs/amazon-dsstne#68]
The AMI for Amazon DSSTNE (ami-d6f2e6bc) includes a non-empty .bash_history file.

As is turns out, there's nothing sensitive in it, but this is in contradiction with best practices :) http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/building-shared-amis.html

**Comment by tristanpenman** [comment]
@juliensimon, thanks for the pointer to that Guideline doc. Our latest AMI (ami-25c0eb32 in US East 1) now follows those best practices.
