### ISSUE TITLE
What the @#$% is this?

### ISSUE THREAD

**Issue by scottlegrand** [amznlabs/amazon-dsstne#7]
In NNNetwork.cpp, the following lines appear:

        if (maxMemory == 131072 ) {
	    maxMemory = 138943;
	}

This either looks like some debugging code I may have added tracking down the maxSparse bug or something someone kludged in.  Is this familiar to anyone?

**Comment by rgeorgej** [comment]
I have fixed the code the code I think this was kludged in while debugging the Sparse kernel

**Comment by scottlegrand** [comment]
Heh, I'll totally take the blame here!

**Comment by romerocesar** [comment]
cleaned up a52447697f49e3ab0ccdfe6b3c8f349f23f1da65
