### ISSUE TITLE
Total training time when setting np=1,2... with GPU

### ISSUE THREAD

**Issue by bgpatel** [amznlabs/amazon-dsstne#72]
This is not an issue but more a question on the results that get displayed after training:
It shows:
Total training time 21.25 GPU Memory usage: 265000 KB

Ques: I am assuming this training time is in sec?
Ques: Memory usage reported is the GPU memory used?
Thanks

**Comment by tristanpenman** [comment]
Although it is not clear from the output, `Total Training Time` refers to wall-clock time for training, in seconds.

And 'GPU Memory usage' refers to the amount of GPU memory in use at the time that training completes.
