### ISSUE TITLE
What's the purpose of encoder?

### ISSUE THREAD

**Issue by sgkim126** [amznlabs/amazon-dsstne#83]
Currently, [main.cpp](https://github.com/amznlabs/amazon-dsstne/blob/master/src/amazon/dsstne/utils/main.cpp) is compiled to "encoder", and I cannot find any document of it.

As I see it, main.cpp is outdated and it was subdivided into Predict.cpp, Train.cpp and NetCDFGenerator.cpp. Is there any purpose of main.cpp and encoder?

**Comment by scottlegrand** [comment]
It's my development app for rapid compile/link/debug cycles.  It's also an
example of how to call the library directly.  For examle, using DSSTNE as
it is used in encoder, I have called DSSTNE from a python extension, giving
it a de facto python interface.  That will eventually get into the tree
when we formalize how to do so.

Scott

**Comment by sgkim126** [comment]
Oh, I got it.
Thank you, scott.
