### ISSUE TITLE
Not able to compile dsstne due to the gpu architecture

### ISSUE THREAD

**Issue by beeva-ivanfernandez** [amznlabs/amazon-dsstne#84]
Hi,

I am trying to setup DSSTNE on AWS following this [guide](https://github.com/amznlabs/amazon-dsstne/blob/master/docs/getting_started/setup.md#setup-on-aws) but I have found problems regarding my gpu architecture

ubuntu@ip-10-10-12-74:~/amazon-dsstne/src/amazon/dsstne$ make
cd engine && make
************  RELEASE mode ************
make[1]: Entering directory `/home/ubuntu/amazon-dsstne/src/amazon/dsstne/engine'
nvcc -use_fast_math --ptxas-options="-v" -gencode arch=compute_50,code=sm_50 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_60,code=sm_60 -DOMPI_SKIP_MPICXX -std=c++11 -I/usr/local/cuda/include -IB40C -IB40C/KernelCommon -I/usr/local/include -I/usr/local/openmpi/include -I/usr/include/jsoncpp -I../utils -I../engine  -c kernels.cu
nvcc fatal   : Unsupported gpu architecture 'compute_60'
make[1]: *** [kernels.o] Error 1
make[1]: Leaving directory `/home/ubuntu/amazon-dsstne/src/amazon/dsstne/engine'
make: *** [lib/libdsstne.a] Error 2

In my EC2 instance I have previously installed TensorFlow plus CUDA, CUDNN and Bazel. Versions are:
tensorflow-**0.11.0**rc0-cp27-none-linux_x86_64
cuda-repo-ubuntu1404_**7.5**-18_amd64
cudnn-7.5-linux-x64-**v5.1**
bazel-**0.3.2**

Everything seems to work fine but DSSTNE.

**Comment by brunosez** [comment]
go to 
https://github.com/amznlabs/amazon-dsstne/issues/58

**Comment by beeva-ivanfernandez** [comment]
thank you @brunosez, I tried that buty got same outcome. I think some cuda or cudnn might be not compatible

**Comment by scottlegrand** [comment]
remove the cuda_60 stuff and it will compile.  This is a CUDA 8 issue.
DSSTNE needs CUDA 8 to compile for Pascal class GPUs, but AWS instances
come with CUDA 7.0 I believe.

The long-term fix is upgrading the CUDA AMI toolkit to 8.0.

**Comment by beeva-ivanfernandez** [comment]
@scottlegrand, what you are meaning saying 'remove the cuda_60 stuff '?, Do I need to install CUDA 8 to my instance just for compiling?

thank you!!

**Comment by beeva-ivanfernandez** [comment]
I finally added CUDA 8 and Cudnn to the path and it seems it is working now.

**Comment by tristanpenman** [comment]
Glad to hear you got it working, @beeva-ivanfernandez. 

I'll follow up on Scott's earlier advice, for the benefit of anyone else who stumbles across this issue. In Makefile.inc, which can be found under `src/amazon/dsstne`, there are some compiler flags that can be removed when using CUDA 7. The specific flags to remove are `-gencode arch=compute_60,code=sm_60`.

You will still need to install cuDNN to compile DSSTNE, but this will allow you to use CUDA 7.

I'm going to close this ticket for now, but it can be reopened if there are any further issues.

**Comment by scottlegrand** [comment]
Switch to CUDA 8 or remove the compilation for the cuda_60 architecture.
The long-term solution is CUDA 8, but it was just finally officially
released.
