### ISSUE TITLE
example dataset/model cannot be downloaded (access denied)

### ISSUE THREAD

**Issue by szilard** [amznlabs/amazon-dsstne#91]
Wanted to try out the example https://github.com/amznlabs/amazon-dsstne/blob/master/docs/getting_started/examples.md

But downloading the sample data https://s3-us-west-2.amazonaws.com/amazon-dsstne-samples/data/ml20m-all and sample network https://s3-us-west-2.amazonaws.com/amazon-dsstne-samples/configs/config.json fails:

```
<Error>
<Code>AllAccessDisabled</Code>
<Message>All access to this object has been disabled</Message>
<RequestId>00DCD5FF7D395B6A</RequestId>
<HostId>
ibDnw8wMxjjhRL2sYFuWtsAo3Q3ERMQVxdNsS4owyZXlCcPWqOjSjxxdiXDihwsUAzlilPVPXbI=
</HostId>
</Error>
```

**Comment by tristanpenman** [comment]
Thanks for letting us know, @szilard. I'm looking into it and will hopefully be able to provide updated links within the next day.

In the mean time, let me know if you would like to arrange to access to the file through some temporary means such as Dropbox.

**Comment by szilard** [comment]
@tristanpenman Next day is fine :) thanks for looking into this.

Btw the reason to look into this now specifically is that I'm hosting @scottlegrand at my meetup in LA on Thursday: http://datascience.la/dsstne-a-new-deep-learning-framework-for-large-sparse-datasets/

I'm also the author of this benchmark: https://github.com/szilard/benchm-ml

**Comment by tristanpenman** [comment]
@szilard and @norangLemon - URLs for the MovieLens sample data have been updated in commit 6714bfd.

I'm going to close this ticket, but please feel free to re-open it if you have any trouble accessing the files at the new location.
