### ISSUE TITLE
movie lens dataset link is invalid

### ISSUE THREAD

**Issue by norangLemon** [amznlabs/amazon-dsstne#92]
```
wget https://s3-us-west-2.amazonaws.com/amazon-dsstne-samples/data/ml20m-all
```
Dataset link in the [example](https://github.com/amznlabs/amazon-dsstne/blob/master/docs/getting_started/examples.md) is invalid now:

![2016-10-25 3 59 06](https://cloud.githubusercontent.com/assets/11316830/19675911/09458186-9acc-11e6-92f0-b1ea93181153.png)

**Comment by tristanpenman** [comment]
Thanks for heads up @norangLemon. This has already been raised in issue https://github.com/amznlabs/amazon-dsstne/issues/91, which where progress will be tracked.
