### ISSUE TITLE
Creation of docker fails with missing cudnn file

### ISSUE THREAD

**Issue by benitezmatias** [amznlabs/amazon-dsstne#96]
Following the example of docker setup, creation of docker fails due to missing cudnn header file:

In file included from NNTypes.cpp:13:0:
GpuTypes.h:23:19: fatal error: cudnn.h: No such file or directory
 #include <cudnn.h>
                   ^
compilation terminated.
make[1]: Leaving directory `/opt/amazon/dsstne/src/amazon/dsstne/engine'
make[1]: *** [NNTypes.o] Error 1
make: *** [lib/libdsstne.a] Error 2

**Comment by scottlegrand** [comment]
Yeah, you guys *still* need to come to some sort of resolution w/r to
licensing cuDNN: Convolution, MaxPooling, LRN, Batch Normalizartion, and
RNNs either do or will rely on it.

**Comment by tristanpenman** [comment]
My recent changes to the Dockerfile included in this repo should address the cuDNN-related compiler errors. The new Dockerfile inherits from one of NVIDIA's public Docker images, which has CUDA 7.5 + cuDNN 5.1 installed. You'll have to build the Docker image yourself, as it the end user's responsibility to accept the NVIDIA's EULA.

The Makefile has also been updated to remove some compiler flags that assumed CUDA 8 would be available.
